### ISSUE TITLE
Release 4.2.0.0 has incorrect nuspec configuration

### ISSUE THREAD

**Issue by scottmatthews343** [PowerShell/StorageDsc#178]
ISSUE TITLE:
Release 4.2.0.0 has incorrect nuspec configuration

ISSUE DESCRIPTION:
I cant see where your deployment scripts are but I believe there is an issue when generating a nu-spec file for release. In release 4.1.0.0 the nu-spec was:

```xml
  <metadata>
    <id>StorageDsc</id>
    <version>4.1.0.0</version>
```

However in release 4.2.0.0 it is
```xml
  <metadata>
    <id>StorageDsc</id>
    <version>4.2.0</version>
```
Notice the missing ".0"

The result of this is that the module is installed to C:\Program Files\WindowsPowerShell\Modules\StorageDSC\4.2.0 but the psd1 file has "4.2.0.0" specified and thus makes it an invalid module. Running Get-Module -ListAvailable fails to return 4.2.0.0. 

This should be a pretty simple fix. I'm happy to have a look if you can point me in the right direction? I don't see any scripts that deal with packaging this module

#### Details of the scenario you tried and the problem that is occurring
Tried installing this module from our Artifactory instance using Install-Module. The command completes successfully but the resultant module is not valid and cannot be imported. 

Trying to import the module via its psd1 yields the underlying reason
```powershell
PS D:\Code> Import-Module 'C:\Program Files\WindowsPowerShell\Modules\StorageDsc\4.2.0\Stora
geDsc.psd1'
Import-Module : The ModuleVersion key in module manifest 'C:\Program
Files\WindowsPowerShell\Modules\StorageDsc\4.2.0\StorageDsc.psd1' specifies module version '4.2.0.0'
which does not match its version folder name at 'C:\Program
Files\WindowsPowerShell\Modules\StorageDsc\4.2.0'. Change the value of the ModuleVersion key to match
the version folder name.
At line:1 char:1
+ Import-Module 'C:\Program Files\WindowsPowerShell\Modules\StorageDsc\ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Program File...StorageDsc.psd1:String) [Import-Module
   ], InvalidOperationException
    + FullyQualifiedErrorId : Modules_InvalidModuleManifestVersion,Microsoft.PowerShell.Commands.ImportM
   oduleCommand
```

#### Suggested solution to the issue
Update the nu-spec to have the full 4 part version number

#### The operating system the target node is running
```powershell
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1803
WindowsBuildLabEx    : 17134.1.amd64fre.rs4_release.180410-1804
OsLanguage           : en-GB
OsMuiLanguages       : {en-GB}
```

#### Version and build of PowerShell the target node is running
```powewshell
Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
N/A

**Comment by PlagueHO** [comment]
Hi @mrhockeymonkey - Leaving off the trailing 0 in the nuspec is actually something Nuget does rather than something we do during the publish process. However, this shouldn't cause a problem when using `Install-Module StorageDsc` from the PSGallery.

I gave it a try myself and it all looks OK:
![image](https://user-images.githubusercontent.com/7589164/47834846-ffa4e700-de05-11e8-9e4d-2d284755efd1.png)

How did you install the module?

**Comment by mrhockeymonkey** [comment]
Indeed you are correct it looks like I don't have the issue when I try from PSGallery on my home laptop. At work we use Artifactory to cache PSGallery modules for internal use (we have no direct internet access). Artifactory is the equivalent of a standard NuGet repository. 

I'll test this by spinnig up a separate NuGet server, not Artifactory, and see what happens. There is a chance it's Artifactory at fault.

**Comment by PlagueHO** [comment]
Hi @mrhockeymonkey - I use Sonatype Nexus at work which is similar to JFrog Artifactory and we use it to proxy the modules. However, we're using it as a "proxy" rather than a mirror. You could use PSGallery on a machine connected to the internet to pull down the modules using ```Install-Module``` and then bring the files into your internal network manually and then use the ```Publish-Module``` command to publish them back up to Artifactory.

**Comment by mrhockeymonkey** [comment]
Hi @PlagueHO feel free to close this (apologies for not replying sooner). As mentioned its a weird quirk with artifactory, turns out this only happens when I install directly from artifactory's cache and not when I use it as a proxy. The only reason I was doing that at all was because i had no way to specify the version I wanted explicitly in Ansible but that is getting solved in https://github.com/ansible/ansible/pull/46516 so no need for this issue anymore. 

thanks for your feedback.

**Comment by psychonic** [comment]
I just ran into this same issue with ComputerManagementDsc and xWebAdministration, installing packages manually cached from PSGallery in a local file share as a repository. The nuspec has the truncated version number, so the modules install to the wrong folder name.

> Leaving off the trailing 0 in the nuspec is actually something Nuget does rather than something we do during the publish process.

Some other Microsoft modules and third-party modules don't seem to have this issue. Are there still no plans to fix it?

**Comment by psychonic** [comment]
Looks like there is a separate issue for this at the PSGallery level. More info is at https://github.com/PowerShell/PowerShellGallery/issues/55

**Comment by PlagueHO** [comment]
Hi @psychonic - this has been a long time problem with PowerShellGet - but more correctly an annoying behavior of Nuget itself. It will affect all DSC Resource modules published to the PSGallery unfortunately.
